def switchToAlert(driver, sleep):
    driver.find_element_by_xpath("//a[@href='SwitchTo.html']").click()
    sleep(1)
    driver.find_element_by_xpath("//a[@href='Alerts.html']").click()
    sleep(1)
    driver.find_element_by_xpath("//a[@href='#OKTab']").click()
    driver.find_element_by_xpath("//button[@onclick='alertbox()']").click()
    sleep(1)
    driver.switch_to.alert.accept()
    driver.find_element_by_xpath("//a[@href='#CancelTab']").click()
    sleep(1)
    driver.find_element_by_xpath("//button[@onclick='confirmbox()']").click()
    sleep(1)
    driver.switch_to.alert.dismiss()
    print(driver.find_element_by_xpath("//p[@id='demo']").text)

    driver.find_element_by_xpath("//a[@href='#Textbox']").click()
    sleep(1)
    driver.find_element_by_xpath("//button[@onclick='promptbox()']").click()
    driver.switch_to.alert.send_keys("Python User")
    sleep(2)
    driver.switch_to.alert.accept()
    print(driver.find_element_by_xpath("//p[@id='demo1']").text)


def switchToWindow(driver, sleep):
    driver.find_element_by_xpath("//a[@href='SwitchTo.html']").click()
    sleep(1)
    driver.find_element_by_xpath("//a[@href='Windows.html']").click()
    sleep(1)
    driver.find_element_by_id("dismiss-button").click()
    sleep(1)
    driver.find_element_by_xpath("//a[@href='#Tabbed']").click()
    sleep(1)
    driver.find_element_by_xpath("//a[@href='#Seperate']").click()
    sleep(1)
    driver.find_element_by_xpath("//a[@href='#Multiple']").click()
    sleep(1)

def switchToIframe(driver, sleep):
    driver.find_element_by_xpath("//a[@href='SwitchTo.html']").click()
    sleep(1)
    driver.find_element_by_xpath("//a[@href='Frames.html']").click()
    sleep(1)
    # driver.find_element_by_xpath("//a[@href='#Single']").click()
    # sleep(1)
    # driver.find_element_by_xpath("//a[@href='#Multiple']").click()
    # sleep(1)